ingress:
  enabled: true
  domain: ""

frontend:
  image:
    registry: "ghcr.io/alliander-opensource"
    name: "pokertool-frontend"
    tag: "v1.0.0"
  replicas: 1

backend:
  image:
    registry: "ghcr.io/alliander-opensource"
    name: "pokertool-backend"
    tag: "v1.0.0"
  replicas: 1
